language: java
before_script:
- cd Api
deploy:
  provider: heroku
  api_key:
    secure: VMb8jQTe2bvAFAy8Z4GZA31E9cerYJtp+iEXsbVNkC8GnGkWrUS23ssMP9YBQzTZRioeykSSOe5kz8Ge5yW8YQwG0usoe+vo6gU7DX5W6p8rolYMEuSDVShgLEmtvY+7Pu4wOkUvHwAOL7MAsy94DJiXoJ4dG95t+huDQt3oJsCYhWH6tnCrVAanapO2aqBsLRyd0NmomfGhdNwU5r8j2fy0DRZLXx+Ry/LBDKWnFkeGz5xarZEVNkCY4aXMpGlRsWO1xAGWhH+0ONovr9ayCUjJGXGHfoxKeMij+HdyxnrpKpxd+Ymto630oi9qSvycxVWGAvdAmzbRqWEPnRGAdcEQA3mAZ1EKrc84ycORp5E44ALrpQhfpJZZsqELoDQB6jV7f6/eZbOW4knlSj+ktg7CUR0hqMkY8AY/YyrpuHlb/UHbgcOJU1SZMxrb7/V/W3ZdJN0HmuDGc212IU4qPn/OE8Q+SE72omOtsB51x3EvP8flhARpN0aBU/keap1qj+MFiopKja3mjyfuT0zYUoVvTvCp4G6yevUZIxNCWnerxA2f/RuzlnWz+Xrs7PvcZoOc+NMydYvdhcgmhV2bbx5iiMWDGTdJL0D4bI4MIschCsUYlRUXcK72dy52IBcsiH6xiRKsqjvPK7oCk1qrw1uAxSJ4GU3kiCVTT52lemI=
