matrix:
  include:
    - language: java
      before_script:
        - cd Api
      deploy:
        provider: heroku
        api_key:
            secure: SRVTSfJEke/lRxvszVEO6a5bI2XT0lIkaz+3AUuIwmtSPEe4q6cg3jPPuas3KG8zXv0eK0g6Fgo9je0/O6Ba6a0W5fz9J4WSJIXzsvnfEc+tSG7VvQF5XLXHRYmnj5xaqShoZhYH+BtpEpYiPFt2imLIvQFw19e7pR2LNfp1Dz6QfpEZTa8GfTftP/9y0SEmZv16oq1VRm6nBygjtNdn5LiwlTzLSwVvPdoRyOaq7527kdlKbHQ9meVreFPOuzj1GYiuiQ69noRCZkLs8wqcUZ0ZHamu84kiBpVtauwWY2BaQJYOcWHKFYpSxfEuvYINmvDsx/Uhvc5qws/+8fLzjOnETpfpkzLizKC+vf4aoccg7gqUm7yiVGWWbOUrFPx08E0zXMLUeQKXwrPWnQnEfMlt+SRIJiS51wlZob7ftNDW6p/ygg2CAswRBtaqi50bFeEnJESO4m5nFL8lVOpY+F9yZ2buiSxOAIPE2/L09YlaJ8oLwYXkbV9d9kK/E0UJlwAyhIEsgrITQJNiFZHIRE6CwatI/ZqIuLvl4OLi7i9y2tpNI/5TTrpRhiLSAAR7pCdXk+mfiZFzGqRWw1ySBG8eweW0ov7UN9aX4cRj3PWMfxs0/Z+bWfFUxDobI45LzdSSC9yHrMIMAQKPUqQYOYa+80YQH3TI9yzoiHx7ysk=
        app: api-servify
        on:
          branch: master

    - languaje: node_js
      before_install:
        - npm update
      install:
        - npm install
      before_script:
        - cd webservify
      branches:
        only:
        - master
      after_success:
        - git config --global user.name "FennemaRL"
        - git config --global user.mail "ld.fennema@gmail.com"
        - git remote rm origin 
        - git remote add origin https://FennemaRL:${GH_TOKEN}@github.com/FennemaRL/Servify.git
        - npm run deploy
