language: java
before_script:
- cd Api
deploy:
  provider: heroku
  api_key:
    secure: dLtXHQoHSr537SxW6g3DpUqdo/936D1ulI2PgJ22O/mpMkG1IbZwDk0ot7APbMykeixMCMKCf1w6SMg2l2HiJzb+pp1u4qVL80mfQwEurUqsusPfwl8Jb+go9qhS0DZ4tiiqB5E1WJkVdDSvvQVte6cC7nGCHppmMdfS12xlxszhkZ5HNgFpgaH1pakmmCdHG9XG2OIf+vaymkxiF9D9fNb1JfaMewz3C9Wt+gQw0qNTlwkgec0r4Q2+zWA87LUXRxPYahnHVRWRUOLjnoiZ5hOIPimqxOtjyh/eZpFEnmGTZhHSacjtD3n4QGkemkvr2l8gEyfRGoixGFOaxUxVCfTFnPHj/FQLeq55h6D2f8BoHyKl3ns2kLhD5feVfA4ieARnPFAJwNpeRs2xzOPY0rBnxMkxGBA6Ikd3dVWBalOmMaYqHktDlOWYm7AqJMljTH3Cjlr/XJR3Tic0bbALfXpAzw5mJFbTu4ts6qad1Mb3kZsPj5Exaxde8BMaD5KA2nQ/buXg/QeWNSsl12g/Wp6tlY04kzXd8Tn5MF9aBDEVR300QpFyzRqu21ZnIBEIx2AhsQXE+4038DNIXCIBh9e+lbkP5OFBP7EKvAPe+ey0HheJMKQgh0D2K5mizOwt6W8UeFRe/amlTEMpzOphsKbyPNR0nu/z4ELH3kd+ywo=
