language: java

before_script:
  - cd Api
deploy:
  provider: heroku
  api_key:
    secure: afscYBzrJTn4Ec2RmH41E3NlPXamZnz9CkKdCtUUSjH22WsJlNPCwacEfoxyFUSpw0UkG81/BxvMUHY9r9QNNq67VjsMux8Nb1mIdsGicLHgdW9a2u/ZlmkXxQL6/A49DRogQWk64pqPlmSU/ZIFi0ljBe+wQTQ5wH6PoECBTILmD0li5nWX9pxr3La6bh+J6u/5tnhREJ3mBBvNfbzHAzcOZrjryCrbpdFG/+BQmcpJvfPabMZjSRA/KhKeAMVxApHOht70gSlfO/oIEHCjfYyeBK7p6oyAkh6i2P2WEEu1ARL9ZVIZ8uHLFhGJqzy1oviRDsJh+y9bayZ5uGQjn3BjHCRAoAI3Y6mfXLlI/gJYKMDOujpnjQ96VUWZet1LaBedkX5F6dKjjbooI0R8/vnpD9xy/RZJwbofIQWH0HHKKcB+3ncMy8CniVSnuo+aw0TK1sgSyVWt0OFL8lvljayVFeVUFO2HskyfUqdm4QKdz3AEklE4nNigcI9xaxEjiRJHfDaWSxdb97YEddNUASmor0yW1z44ZZ3AKcOgOY1lfE840SCUb4IMD8abYUZaRC3GxqD0+Y4lwLvKz4/ot7CLK6dax3QBlFr3q4TbMTtk6bWT2C4TO8R51wi0QYzXPLoxWKR+wheegbiCJ/m5LCRnVWXDrxmRTqU9KzKeS5k=
