matrix:
  include:
    - language: java
      before_script:
        - cd Api
      deploy:
        provider: heroku
        api_key:
            secure: ${Heroku_Key}
        app: api-servify
        on:
          branch: master

    - languaje: node_js
      node_js:
        - "12"
      before_install:
        - cd webservify
      script:
        - echo "FennemaRL"
      deploy:
        provider: script
        script:
        - git config --global user.name "FennemaRL"
        - git config --global user.mail "ld.fennema@gmail.com"
        - git remote rm origin 
        - git remote add origin https://FennemaRL:${GH_TOKEN}@github.com/FennemaRL/Servify.git
        - git push origin :gh-pages
        - npm run deploy
        on:
          branch: master
