language: java
before_script:
- cd Api
deploy:
  provider: heroku
  api_key:
    secure: csg9IrgUkevsRADKDBd9z/a3LG/vSR3IBvorEB9om9bCveypUSZEBkdPun+MoBR2pkwcj7T8w+HFldtNLMbU7ZlXz5gpvmW9OCGDCvOn6TnNsPTS6gYygtok54XzusBdwynwWeUV+YOPFh4ILwpK5uEJBcZwUKHcwZsQnchkQypYmFHm4Dk46w5+VaOWFSWE5Snj0NgQmbV1X4CvjnlPvqLk0xxgXbvD6Thvj/pNKI+OVxmuECFuWh3HoIqHyIm5mwUdra5g3SbKvd7OpI4iIip6nhKUhItXiCNmy1QW2DGyma+YKVQYUtaCalv5NXnMuBxstm3LZru9uiiia5/vlzmlX8ne5Fx4mZYO/bSgLqCluu9lRRcsNkudIpyk5uqwuRSnppEKodQccSW42CgtMPbmVRfJxAs8mbC4sZmae8qdFHc84Fu1flDCG8xhzNW+ao7qhoobAnKyZZ35VWtc9qOp5kpfqPmW6A3hfrBieIap/tn2f8HSPpxpWE0nTU7bz71234+H9wnNLWBZtL2w6iY0L+rQVFT8PUDnvELB8PpO5ZB7mLLhDINqYCxu7KUnG5EadMfccq7BZTe2fWa/k1nOhac6wPO+nCpnZMhXWIuFWZw+dqFmsWNP1T4oIJKPI0iI+VcGhGPrJt0+6ZKg5+URmgCveEvuZm/4nW36sCA=
